import { Box } from '@chakra-ui/react'
import Head from 'next/head'
import Main from '../../layouts/Main'
import Articles from '../../components/Articles'
import { useGetAllArticles } from '../../hooks/articles/useGetAllArticles'
import { Loader } from '../../components/common/Loader'

const ArticlesPage = () => {
	const { articles, isLoadingArticles } = useGetAllArticles()

	return (
		<Box bgColor='brand.background'>
			<Head>
				<title>Klever Academy | Articles</title>
				<meta name='description' content='Generated by Klever Academy' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<Main>
				{isLoadingArticles ? (
					<Box h='calc(100vh - 305px)' display={'flex'} alignItems={'center'} justifyContent={'center'}>
						<Loader />
					</Box>
				) : (
					<Articles articles={articles} />
				)}
			</Main>
		</Box>
	)
}

export default ArticlesPage
