import { Box } from '@chakra-ui/react'
import Head from 'next/head'
import Article from '../../../components/Articles/Article'
import { useGetArticle } from '../../../hooks/articles/useGetArticle'
import Main from '../../../layouts/Main'
import { useRouter } from 'next/router'

const ArticleSlug = () => {
	const router = useRouter()
	const { slug } = router.query
	const id = slug && slug.split('--')[1]
	const { article } = useGetArticle(id)

	return (
		<Box bgColor='brand.background' minH='100vh'>
			<Head>
				<title>Klever Academy | {article?.title || 'Article'}</title>
				<meta name='description' content='Generated by Klever Academy' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<Main>{article && <Article article={article} />}</Main>
		</Box>
	)
}

export default ArticleSlug
