import { Box, Text } from '@chakra-ui/react'
import Head from 'next/head'
import Main from '../layouts/Main'
import Image from 'next/image'
import BuildingImage from '../assets/img/building.svg'

export default function Earn() {
	return (
		<Box bgColor='brand.background'>
			<Head>
				<title>Klever Academy | Earn</title>
				<meta name='description' content='Generated by Klever Academy' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<Main>
				<Box
					h='calc(100vh - 305px)'
					display='flex'
					alignItems='center'
					justifyContent='center'
					flexDirection='column'
				>
					<Image width='512px' height='512px' src={BuildingImage} alt='Not Found' />
					<Text color='white' textTransform='uppercase' fontSize='2xl' fontWeight='bold'>
						We are working on it! Stay tuned for more information!
					</Text>
				</Box>
			</Main>
		</Box>
	)
}
