import { Box, Divider } from '@chakra-ui/react'
import Head from 'next/head'
import Main from '../layouts/Main'
import Hero from '../components/Hero'
import SearchHeader from '../components/SearchHeader'
import ResourcesGrid from '../components/Resources/ResourcesGrid'

export default function Home() {
	return (
		<Box bgColor='brand.background'>
			<Head>
				<title>Klever Academy</title>
				<meta name='description' content='Generated by Klever Academy' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<Main>
				<Box>
					<Hero />
					<Divider />
					<SearchHeader />
					<ResourcesGrid />
				</Box>
			</Main>
		</Box>
	)
}
