import Head from 'next/head'
import Main from '../layouts/Main'
import Hero from '../components/Hero'

export default function Home() {
	return (
		<div>
			<Head>
				<title>Klever Academy</title>
				<meta name='description' content='Generated by Klever Academy' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<Main>
				<Hero />
			</Main>
		</div>
	)
}
