import { Box, Button, Divider, Flex, Link, Text } from '@chakra-ui/react'
import Head from 'next/head'
import Main from '../layouts/Main'
import Hero from '../components/Hero'
import ResourcesGrid from '../components/Resources/ResourcesGrid'
import Earn from '../components/Earn'
import NextLink from 'next/link'

export default function Home() {
	return (
		<Box bgColor='brand.background'>
			<Head>
				<title>Klever Academy</title>
				<meta name='description' content='Generated by Klever Academy' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<Main>
				<Box>
					<Hero />
					<Divider />
					<Text color='white' fontSize='3xl' my={6} fontWeight='bold'>
						Featured Content
					</Text>
					<ResourcesGrid />
					<Flex justifyContent='center' mt={10}>
						<NextLink href='/explore' passHref>
							<Link
								rounded='sm'
								bg='brand.primary'
								color='white'
								fontWeight='bold'
								textTransform='uppercase'
								px={6}
								py={4}
								_hover={{
									opacity: 0.8,
								}}
							>
								Explore All Content
							</Link>
						</NextLink>
					</Flex>
					<Earn />
				</Box>
			</Main>
		</Box>
	)
}
