import { Box } from '@chakra-ui/react'
import Head from 'next/head'
import Video from '../../../components/Videos/Video'
import { useGetVideo } from '../../../hooks/videos/useGetVideo'
import Main from '../../../layouts/Main'
import { useRouter } from 'next/router'

const Slug = () => {
	const router = useRouter()
	const { slug } = router.query
	const id = slug && slug.split('--')[1]
	const { video } = useGetVideo(id)

	return (
		<Box bgColor='brand.background' minH='100vh'>
			<Head>
				<title>Klever Academy | {video?.title || 'Video'}</title>
				<meta name='description' content='Generated by Klever Academy' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<Main>{video && <Video video={video} />}</Main>
		</Box>
	)
}

export default Slug
