import { Box, Text } from '@chakra-ui/react'
import Head from 'next/head'
import Main from '../../layouts/Main'
import Videos from '../../components/Videos'

const VideosPage = () => {
	return (
		<Box bgColor='brand.background'>
			<Head>
				<title>Klever Academy</title>
				<meta name='description' content='Generated by Klever Academy' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<Main>
				<Videos />
			</Main>
		</Box>
	)
}

export default VideosPage
